### PR TITLE
Allow API to properly return undecoded outputs

### PR DESCRIPTION
**Pull request by mewald55**
Here's a hack I've used to fix the API for outputs with undecoded output addresses...

The problem happens when there is a row in the outputs table with addr="0", but the API cant find that row in the address table, so the entire output is discarded, leaving bitcoins unaccounted for.

There is probably a cleaner way to do this, but this was quick. I haven't actually tested the change in sqlchain.sql because I'm working on a synced version, but it should work. You don't have to commit this hack, its just an idea :)

### CODE REVIEW

**Comment by neocogent** [comment]
Is there a case where zero addr_id is stored in the outputs table? That seems like it should be an error or maybe I'm just forgetting something I coded long ago. I'm ok with adding a zero id row into table at creation as a failsafe against mysql errors. I'd just like to know if it's a bug causing zero addr_id to occur.

Is your pkh check value correct? Says '0\x00\x00.... first digit is ascii zero not \x00. Either way can write as `'\0'*20` to get 20 zero bytes and easier to read.

I'll look into this a bit more before deciding to merge.

**Comment by neocogent** [comment]
I had a look and indeed when a scriptPubKey doesn't have an output address, eg. OP_RETURN, it does insert a zero addr_id. Just a special case I never looked at much. The actual data is stored in the blob file (even if no-sigs=True) and it should be a TODO for the API to get the actual value (depending on what it needs ).

Overall I'd say this PR is a good idea. I'd like to see the pkh check simplified to `'\0'*20` (assuming that works ok) before merge.

**Comment by mewald55** [comment]
Ya, that long string is a bit strange because I'm inserting the ascii '0' into the addresss table, and mysql right-pads with 19 of zero bytes '0x00'.

I suppose we could do  `'0'+'\x00'*19` , or just change what addr value is in the 0 row... I'll test it out in 1-2 days when my sync finishes.

**Comment by neocogent** [comment]
Oh, I see. The address table values are binary so I'd think it is better to use a binary 20 byte pkh as null address. It's more consistent  and then the check is simply '\0'*20. I think if you insert a '' (empty string) it should fill all zeros. Will try here as test.

edit - yes, can confirm insert empty string stuffs all zeros.

**Comment by neocogent** [comment]
I changed slightly and went ahead on merge.

**Comment by neocogent** [comment]
I committed another fix needed to make this null address work.

Turns out pkh == '\0'*20 is a valid address and used on testnet (maybe on mainnet too but did not check). When a real one is found it blows up due to empty address. But a real one has a non-zero addr_id so it can work fine. Just needed to make sure addr2id detects correctly and mkaddr encodes correctly. Works ok now in my testing on re-sync with real data.

**Pull request merged**
